// Modelos.java
package com.example.activities;

public class Modelos {
    private String[] modelosCDeCarros = {
            "Ford Mustang",
            "Chevrolet Camaro",
            "Dodge Charger",
            "BMW M3",
            "Audi R8",
            "Mercedes-Benz AMG GT",
            "Porsche 911",
            "Ferrari 488",
            "Lamborghini Huracán",
            "Aston Martin DB11",
            "Nissan GT-R",
            "McLaren 720S",
            "Jaguar F-Type",
            "Tesla Model S",
            "Ford F-150",
            "Chevrolet Silverado",
            "Dodge Ram 1500",
            "Toyota Tacoma",
            "Honda Civic",
            "Toyota Corolla",
            "Ford Fiesta",
            "Hyundai Elantra",
            "Kia Optima",
            "Volkswagen Golf",
            "Subaru Impreza",
            "Mazda MX-5 Miata",
            "BMW Z4",
            "Audi TT",
            "Mercedes-Benz SLK",
            "Lexus LC",
            "Infiniti Q60",
            "Acura NSX",
            "Chevrolet Corvette",
            "Ford GT",
            "Porsche Cayman",
            "Alfa Romeo Giulia",
            "Maserati Ghibli",
            "Bentley Continental GT",
            "Rolls-Royce Phantom",
            "Bugatti Chiron",
            "Pagani Huayra",
            "Koenigsegg Agera",
            "Lotus Evora",
            "Tesla Model X",
            "BMW X5",
            "Audi Q7",
            "Mercedes-Benz GLE",
            "Volvo XC90",
            "Land Rover Range Rover",
            "Jeep Grand Cherokee",
            "Ford Explorer",
            "Chevrolet Tahoe",
            "Honda CR-V",
            "Toyota RAV4",
            "Nissan Rogue",
            "Subaru Outback",
            "Mazda CX-5",
            "Hyundai Santa Fe",
            "Kia Sorento",
            "Volkswagen Tiguan",
            "Jeep Wrangler",
            "Land Rover Defender",
            "Mitsubishi Pajero",
            "Suzuki Jimny",
            "Toyota Land Cruiser",
            "Lexus LX",
            "Mercedes-Benz G-Class",
            "Ford Bronco",
            "Chevrolet Blazer",
            "Honda Pilot",
            "Dodge Durango",
            "Tesla Model 3",
            "Nissan Leaf",
            "Chevrolet Bolt",
            "BMW i3",
            "Audi e-tron",
            "Mercedes-Benz EQC",
            "Jaguar I-PACE",
            "Hyundai Kona Electric",
            "Kia Soul EV",
            "Volkswagen ID.4",
            "Polestar 2",
            "Rivian R1T",
            "Lucid Air",
            "Porsche Taycan",
            "Ford Mustang Mach-E",
            "Tesla Model Y",
            "GMC Hummer EV",
            "Bollinger B1",
            "Alfa Romeo Stelvio",
            "Maserati Levante",
            "Bentley Bentayga",
            "Lamborghini Urus",
            "Rolls-Royce Cullinan",
            "Aston Martin DBX",
            "Ferrari Purosangue",
            "Mercedes-Maybach GLS",
            "Audi Q8",
            "BMW X7",
            "Volvo XC60"
    };

    // Método getter para acessar o array
    public String[] getModelosCDeCarros() {
        return modelosCDeCarros;
    }
}
